# gotta add:
# fish
# xonsh
# tcsh
# nushell
# elvish
# to the profile stuff


precmd() {
    print -rP "( %F{blue}%n%f @ %F{blue}%m%f - %F{blue}%~%f )"
}
PROMPT="%F{green}>>%f "

alias cd..="cd .."
alias cd.="cd ."

if [ ! -f ~/.nobanner ]; then
    cat /etc/polaris/banner
fi

source /etc/polaris/lib.sh

export EDITOR=$(/usr/bin/python3 /usr/share/polaris/pcore-shack.py editor)
export TERMINAL=$(/usr/bin/python3 /usr/share/polaris/pcore-shack.py terminal)
export BROWSER=$(/usr/bin/python3 /usr/share/polaris/pcore-shack.py browser)

