# gotta add:
# fish
# xonsh
# tcsh
# nushell
# elvish
# to the profile stuff


precmd() {
    print -rP "( %F{blue}%n%f @ %F{blue}%m%f - %F{blue}%~%f )"
}
PROMPT="%F{green}>>%f "

alias cd..="cd .."
alias cd.="cd ."

if [ ! -f ~/.nobanner ]; then
    cat /etc/polaris/banner
fi